# Generated by Django 3.1.5 on 2021-01-21 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('easy', models.CharField(blank=True, max_length=27, null=True)),
                ('hard', models.CharField(blank=True, max_length=27, null=True)),
                ('tematicas', models.CharField(blank=True, max_length=21, null=True)),
                ('random', models.CharField(blank=True, max_length=27, null=True)),
                ('minuto1', models.CharField(blank=True, max_length=27, null=True)),
                ('minuto2', models.CharField(blank=True, max_length=27, null=True)),
                ('deluxe', models.CharField(blank=True, max_length=42, null=True)),
                ('replica', models.CharField(blank=True, max_length=27, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VotingPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_1', to='vote.competitor')),
                ('comp_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_2', to='vote.competitor')),
            ],
        ),
    ]
