# Generated by Django 3.1.5 on 2021-01-22 23:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='random',
        ),
        migrations.AddField(
            model_name='competitor',
            name='random_mode',
            field=models.IntegerField(choices=[(0, 'Personajes contrapuestos'), (1, 'Objetos'), (2, 'Imágenes vaiadas'), (3, 'Terminaciones'), (4, 'Temática de actualidad')], default=0),
        ),
        migrations.AddField(
            model_name='competitor',
            name='random_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='deluxe',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=14),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='easy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='hard',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='minuto1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='minuto2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='replica',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='tematicas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=7),
        ),
    ]
