# Generated by Django 3.1.5 on 2021-01-31 21:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20210123_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='min1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, verbose_name='Minuto 1'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='min2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, verbose_name='Minuto 2'),
        ),
    ]
