# Generated by Django 3.1.5 on 2021-03-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_auto_20210204_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='random_mode',
        ),
    ]
