# Generated by Django 3.1.5 on 2021-03-09 05:28

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_competitor_random_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='deluxe',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=14, validators=[django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='easy',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='hard',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='min1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator], verbose_name='minuto 1'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='min2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator], verbose_name='minuto 2'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='random_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='replica',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=9, validators=[django.core.validators.MaxValueValidator]),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='tematicas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=7, validators=[django.core.validators.MaxValueValidator]),
        ),
    ]
