# Generated by Django 3.1.5 on 2021-04-14 04:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0009_auto_20210309_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='tematicas',
        ),
        migrations.AddField(
            model_name='competitor',
            name='tematicas_1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=7, verbose_name='Tematicas 1'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='tematicas_2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=7, verbose_name='Tematicas 2'),
        ),
    ]
