# Generated by Django 3.1.5 on 2021-04-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0010_auto_20210413_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingpoll',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='vote.competitor'),
        ),
    ]
