# Generated by Django 3.1.5 on 2021-04-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0011_votingpoll_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingpoll',
            name='winner',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
