# Generated by Django 3.1.5 on 2021-04-24 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0013_votingpoll_rep_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingpoll',
            name='rep_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
