# Generated by Django 3.1.5 on 2021-05-01 23:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0014_auto_20210424_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='random_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=11, verbose_name='Random Mode'),
        ),
    ]
