name: Testing
on: push

jobs:
  test_vote:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: juradofms
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: browser-actions/setup-chrome@latest
    - name: Set up Chrome
      run: chrome --version
    - uses: nanasess/setup-chromedriver@master
    - name: Set up chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: python manage.py migrate
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
    - name: Test
      run: python manage.py test
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}